### ISSUE TITLE
Synchronisiert mode (Default, Eco, Next Trip) nicht bei Änderung

### ISSUE THREAD

**Issue by Norb1204** [tim2zg/ioBroker.fronius-wattpilot#36] opened 2023-07-15 05:55 UTC
Hallo,

bei mir synchronisiert sich der Datenpunkt mode (Default, Eco, Next Trip) nicht immer wenn ich via set_state bzw. set_mode diesen ändere. 
Wenn ich den Interval to receive des Adapters auf 0 einstelle funktionierts.
(Adapterversion 4.5.1).

Gruß Norb

**Comment by tim2zg** [comment] 2023-07-15 09:01
Hello, thank you for your feedback. 
On my side it works as intended: I think you set the mode wrong. The mode key is known as “lmo” so you can see that under https://github.com/joscha82/wattpilot/blob/main/API.md. So, if you want to set the mode to “Default” you need to set_mode 3, “Next Trip” is 5 and “Eco” is 4.
Hope this helps you,
Best regards!

**Comment by Norb1204** [comment] 2023-07-15 09:18
Hello,
Interval to receive from adapter is set to 5 seconds. 
If I change the set_mode to 3, the mode is updated to "Default", so far OK.
If I set the set_mode to 4 the mode updates to "Eco", also OK.
If I change the set_mode to 3 again, nothing changes in the mode, remains on "Eco".
The update of the mode is quite different sometimes "Default" sometimes "Eco" remains.
If the Interval to receive from the adapter is set to 0 everything works correctly.
BR
Norbert

**Comment by tim2zg** [comment] 2023-07-15 15:44
Hello,
Was a tricky bug to reproduce, it was an issue in the timeout function. The bug is fixed for the normal parser. If you get all parameters, it’s still possible to occur if you get the timing right.
The bug is fixed in version 4.6.0 you can update right now on the beta repositories, until the adapter is in stable repository. 
Best regards

**Closed by tim2zg** 2023-07-15 15:44 UTC

**Comment by Norb1204** [comment] 2023-07-16 06:13
thx
